# MyForum
# Some brief description.

###

# List all articles
# 
# none
GET {{host}}/forum/article

###

# Create an article
# 
# none
POST {{host}}/forum/article
Content-Type: application/json

{
    "body": {
        "id": 0,
        "authorId": 0,
        "publicationDate": "",
        "topic": "body.topic"
    }
}

###

# Search article by Id
# 
# none
GET {{host}}/forum/article/{{param_articleId}}

###

# Create an routes.author
# 
# none
POST {{host}}/routes.author
Content-Type: application/json

{
    "body": {
        "id": 0,
        "username": "body.username",
        "firstName": "body.firstName",
        "lastName": "body.lastName",
        "email": "body.email"
    }
}

###

# Logs routes.author into the system
GET {{host}}/routes.author/login

###

# Get routes.author by user name
GET {{host}}/routes.author/{{param_authorId}}

###

# Updated routes.author
# 
# none
PUT {{host}}/routes.author/{{param_authorId}}
Content-Type: application/json

{
    "body": {
        "id": 0,
        "username": "body.username",
        "firstName": "body.firstName",
        "lastName": "body.lastName",
        "email": "body.email"
    }
}

###

# Delete routes.author
# 
# none
DELETE {{host}}/routes.author/{{param_authorId}}

